"""EZ1-M local-API endpoint discovery tool.

Systematic, **read-only**, rate-limited probe of the inverter's HTTP
server on port 8050. Targets the seven documented endpoints plus a
curated wordlist of plausible undocumented paths.

# Strict safety rules

The EZ1's local HTTP server is fragile (verified 2026-04-27 against
firmware EZ1 1.12.2t; see issue #14 in the bridge repo for the
parallel-connection limitation, and ``docs/troubleshooting.md`` for
the WLAN-volatility quirk). This tool deliberately follows narrow
constraints to avoid disturbing the inverter:

1. **GET only.** No POST/PUT/DELETE/PATCH. Mutating verbs against
   guessed endpoints could trigger irreversible writes; the
   discovery surface is read-only.
2. **No `setX?param=` calls.** ``set*`` endpoints are recorded only
   for *existence*; their parameters are NOT guessed. Calling
   ``/setNetwork?ssid=guess`` could lock the inverter onto a wrong
   network.
3. **Rate limit ≥ 1 s** between probes (configurable up). The EZ1's
   WLAN stack is volatile under load.
4. **Per-probe timeout 5 s**, then skip. Prevents the tool from
   hanging if the inverter momentarily stops responding.
5. **Collision-aware retry once.** Concurrent connections from the
   bridge polling the same inverter are dropped at the device. A
   timeout retries once after the rate-limit pause; a second
   timeout records the probe as ``inconclusive`` rather than
   ``unreachable``.
6. **Watchdog.** After ``CONSECUTIVE_FAIL_LIMIT`` consecutive
   ``unreachable`` probes (default 5) the tool aborts with a clear
   message — the inverter is most likely WLAN-dropped and a
   power-cycle is needed.

# Output

Writes ``findings-<UTC-timestamp>.json`` next to this script with
the full per-endpoint record. The Markdown summary in
``README.md`` is generated by hand from the JSON after a clean run.

# Usage

    uv run python tools/api-discovery/probe_endpoints.py \\
        --host 192.168.3.24 --port 8050

Set ``--rate-limit-seconds`` higher (e.g. 2.0) to be even kinder
to the inverter. Set ``--no-set-endpoints`` to skip even the
existence probe of ``set*`` paths.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx

# --- Wordlist ---------------------------------------------------------------

# Documented baseline endpoints — the seven the bridge talks to. Probing
# them at the top of the run confirms the inverter is reachable before
# we burn time on the speculative wordlist.
KNOWN_ENDPOINTS: tuple[str, ...] = (
    "/getDeviceInfo",
    "/getOutputData",
    "/getMaxPower",
    "/getAlarm",
    "/getOnOff",
)

# Speculative read endpoints. Patterns drawn from related solar-inverter
# vendors (Hoymiles, Deye, Growatt local APIs) and ESP32-firmware
# conventions. No promises — most will 404, the point is to surface the
# few that do not.
SPECULATIVE_READ_ENDPOINTS: tuple[str, ...] = (
    "/getStatus",
    "/getInverterDetail",
    "/getNetworkInfo",
    "/getSystemInfo",
    "/getEnergyHistory",
    "/getEnergyDay",
    "/getEnergyMonth",
    "/getEnergyYear",
    "/getDailyEnergy",
    "/getMpptStatus",
    "/getDcVoltage",
    "/getAcVoltage",
    "/getTemperature",
    "/getFrequency",
    "/getInverterStatus",
    "/getWifiInfo",
    "/getSerialNumber",
    "/getModel",
    "/getVersion",
    "/getFirmware",
    "/getUptime",
    "/getCurrentPower",
    "/getRealtimeData",
    "/getStatistics",
    "/getCloudStatus",
    "/getMqttConfig",
    "/getNtpInfo",
)

# Common diagnostic / service patterns.
DIAGNOSTIC_PATTERNS: tuple[str, ...] = (
    "/status",
    "/info",
    "/health",
    "/ping",
    "/api",
    "/debug",
    "/diag",
    "/log",
    "/logs",
    "/version",
    "/api/v1/info",
    "/api/v1/status",
    "/api/v1/data",
    "/api/v2/info",
    "/api/v2/status",
)

# Reboot / factory-reset patterns. These are probed for *existence only*
# (HTTP status / Allow header). Calling them with a body or query
# parameter could obviously be destructive — this tool will never do that.
DESTRUCTIVE_PATTERNS_PROBE_ONLY: tuple[str, ...] = (
    "/reboot",
    "/restart",
    "/reset",
    "/shutdown",
    "/factoryReset",
    "/clearData",
)

# Dashboard / configuration UI guesses.
DASHBOARD_PATTERNS: tuple[str, ...] = (
    "/",
    "/index.html",
    "/index.htm",
    "/admin",
    "/dashboard",
    "/config",
    "/settings",
)

# `set*` endpoints. Existence-only probe. The known two (`setMaxPower`,
# `setOnOff`) are listed for completeness and to verify the discovery
# methodology against the documented surface.
SET_ENDPOINTS_EXISTENCE_ONLY: tuple[str, ...] = (
    "/setMaxPower",
    "/setOnOff",
    "/setNetwork",
    "/setWifi",
    "/setMqtt",
    "/setTime",
    "/setNtp",
    "/setCloud",
)


# --- Constants --------------------------------------------------------------

DEFAULT_HOST = "192.168.3.24"
DEFAULT_PORT = 8050
DEFAULT_TIMEOUT_SECONDS = 5.0
DEFAULT_RATE_LIMIT_SECONDS = 1.0
DEFAULT_CONSECUTIVE_FAIL_LIMIT = 5

# Response body capture: full body for JSON envelopes (the documented
# shape is small — ~200 bytes), truncated for everything else so a stray
# index.html doesn't dominate the JSON file.
JSON_BODY_FULL_CAPTURE_LIMIT = 8 * 1024  # 8 KiB
NON_JSON_BODY_CAPTURE_LIMIT = 500  # chars


# --- Result schema ----------------------------------------------------------


@dataclass
class ProbeResult:
    """Per-endpoint probe outcome. Serialised straight to JSON."""

    endpoint: str
    classification: str  # "known" | "speculative_read" | "diagnostic"
    #                    | "destructive_existence_only"
    #                    | "dashboard" | "set_existence_only"
    outcome: str  # "ok" | "client_error" | "server_error"
    #             | "unreachable" | "inconclusive" | "skipped"
    status_code: int | None = None
    content_type: str | None = None
    content_length: int | None = None
    body_capture: str | None = None
    body_is_json: bool = False
    json_payload: Any = None
    roundtrip_seconds: float | None = None
    retry_used: bool = False
    error_class: str | None = None
    error_detail: str | None = None
    notes: list[str] = field(default_factory=list)


@dataclass
class RunMetadata:
    """Top-level metadata about the discovery run."""

    started_at_utc: str
    finished_at_utc: str | None
    host: str
    port: int
    timeout_seconds: float
    rate_limit_seconds: float
    consecutive_fail_limit: int
    aborted_early: bool
    abort_reason: str | None
    total_probes: int
    by_outcome: dict[str, int]


# --- Probe loop -------------------------------------------------------------


def _classify(endpoint: str) -> str:
    if endpoint in KNOWN_ENDPOINTS:
        return "known"
    if endpoint in SPECULATIVE_READ_ENDPOINTS:
        return "speculative_read"
    if endpoint in DIAGNOSTIC_PATTERNS:
        return "diagnostic"
    if endpoint in DESTRUCTIVE_PATTERNS_PROBE_ONLY:
        return "destructive_existence_only"
    if endpoint in DASHBOARD_PATTERNS:
        return "dashboard"
    if endpoint in SET_ENDPOINTS_EXISTENCE_ONLY:
        return "set_existence_only"
    return "unclassified"


def _capture_body(response: httpx.Response) -> tuple[str | None, bool, Any]:
    """Capture the response body in two flavours.

    For JSON content-types, parse and embed the parsed object so the
    findings file is directly readable. For everything else, truncate
    the raw text so an HTML dashboard page does not balloon the JSON.
    Returns ``(body_capture, body_is_json, json_payload)``.
    """
    content_type = (response.headers.get("content-type") or "").lower()
    text = response.text or ""
    if "application/json" in content_type or text.lstrip().startswith(("{", "[")):
        try:
            payload = response.json()
            full = text[:JSON_BODY_FULL_CAPTURE_LIMIT]
            return full, True, payload
        except (ValueError, json.JSONDecodeError):
            return text[:NON_JSON_BODY_CAPTURE_LIMIT], False, None
    return text[:NON_JSON_BODY_CAPTURE_LIMIT], False, None


def _probe_once(
    client: httpx.Client,
    endpoint: str,
) -> tuple[ProbeResult, bool]:
    """Single GET attempt. Returns (result, is_unreachable_for_watchdog).

    The second tuple element drives the consecutive-fail watchdog: it is
    True only for transport-level unreachability (timeout, connect
    refused), NOT for clean 4xx/5xx responses (which still mean the
    server is alive).
    """
    classification = _classify(endpoint)
    started = time.monotonic()

    try:
        response = client.get(endpoint)
    except httpx.TimeoutException as exc:
        elapsed = time.monotonic() - started
        return (
            ProbeResult(
                endpoint=endpoint,
                classification=classification,
                outcome="unreachable",
                roundtrip_seconds=round(elapsed, 3),
                error_class=type(exc).__name__,
                error_detail=str(exc) or "request timed out",
            ),
            True,
        )
    except httpx.ConnectError as exc:
        elapsed = time.monotonic() - started
        return (
            ProbeResult(
                endpoint=endpoint,
                classification=classification,
                outcome="unreachable",
                roundtrip_seconds=round(elapsed, 3),
                error_class=type(exc).__name__,
                error_detail=str(exc) or "connect error",
            ),
            True,
        )
    except httpx.HTTPError as exc:
        elapsed = time.monotonic() - started
        return (
            ProbeResult(
                endpoint=endpoint,
                classification=classification,
                outcome="unreachable",
                roundtrip_seconds=round(elapsed, 3),
                error_class=type(exc).__name__,
                error_detail=str(exc) or "http error",
            ),
            True,
        )

    elapsed = time.monotonic() - started
    body_capture, body_is_json, json_payload = _capture_body(response)
    if 200 <= response.status_code < 400:
        outcome = "ok"
    elif 400 <= response.status_code < 500:
        outcome = "client_error"
    else:
        outcome = "server_error"

    return (
        ProbeResult(
            endpoint=endpoint,
            classification=classification,
            outcome=outcome,
            status_code=response.status_code,
            content_type=response.headers.get("content-type"),
            content_length=len(response.content),
            body_capture=body_capture,
            body_is_json=body_is_json,
            json_payload=json_payload,
            roundtrip_seconds=round(elapsed, 3),
        ),
        False,
    )


def probe_endpoint(
    client: httpx.Client,
    endpoint: str,
    rate_limit_seconds: float,
) -> ProbeResult:
    """Two-attempt probe with collision-aware retry.

    The EZ1 drops parallel connections; if the bridge is also polling
    the same inverter, our probe SYN can race against the bridge's
    open connection and time out even though the endpoint is fine.
    Retry once after a rate-limit pause; if both attempts time out,
    the result is *inconclusive*, not *unreachable*.
    """
    first, first_unreachable = _probe_once(client, endpoint)
    if not first_unreachable:
        return first

    # Pause before retry — same inter-probe pause to keep the inverter calm.
    time.sleep(rate_limit_seconds)
    second, second_unreachable = _probe_once(client, endpoint)
    second.retry_used = True

    if not second_unreachable:
        second.notes.append(
            f"first attempt failed ({first.error_class}: {first.error_detail});"
            " retry succeeded — likely a transient collision with another"
            " client (e.g. the bridge polling the same inverter)."
        )
        return second

    second.outcome = "inconclusive"
    second.notes.append(
        f"both attempts failed (1st: {first.error_class}, 2nd: {second.error_class}). "
        "Cannot distinguish 'endpoint absent' from 'inverter unreachable' here."
    )
    return second


# --- Run orchestration ------------------------------------------------------


def build_endpoint_list(*, include_set_endpoints: bool) -> list[str]:
    endpoints: list[str] = []
    endpoints.extend(KNOWN_ENDPOINTS)
    endpoints.extend(SPECULATIVE_READ_ENDPOINTS)
    endpoints.extend(DIAGNOSTIC_PATTERNS)
    endpoints.extend(DESTRUCTIVE_PATTERNS_PROBE_ONLY)
    endpoints.extend(DASHBOARD_PATTERNS)
    if include_set_endpoints:
        endpoints.extend(SET_ENDPOINTS_EXISTENCE_ONLY)
    return endpoints


def run_discovery(
    *,
    host: str,
    port: int,
    timeout_seconds: float,
    rate_limit_seconds: float,
    consecutive_fail_limit: int,
    include_set_endpoints: bool,
) -> tuple[RunMetadata, list[ProbeResult]]:
    base_url = f"http://{host}:{port}"
    started_at = datetime.now(tz=UTC)

    endpoints = build_endpoint_list(include_set_endpoints=include_set_endpoints)
    results: list[ProbeResult] = []
    consecutive_unreachable = 0
    aborted_early = False
    abort_reason: str | None = None

    print(f"[probe] target {base_url}, {len(endpoints)} endpoints", file=sys.stderr)
    print(
        f"[probe] timeout={timeout_seconds}s, rate-limit={rate_limit_seconds}s,"
        f" watchdog after {consecutive_fail_limit} unreachable",
        file=sys.stderr,
    )

    with httpx.Client(
        base_url=base_url,
        timeout=timeout_seconds,
        follow_redirects=False,
    ) as client:
        for index, endpoint in enumerate(endpoints, start=1):
            result = probe_endpoint(client, endpoint, rate_limit_seconds)
            results.append(result)

            print(
                f"[probe] {index:3d}/{len(endpoints)} {endpoint:30s}"
                f" → {result.outcome:14s}"
                f" status={result.status_code}"
                f" rtt={result.roundtrip_seconds}s",
                file=sys.stderr,
            )

            if result.outcome == "unreachable":
                consecutive_unreachable += 1
                if consecutive_unreachable >= consecutive_fail_limit:
                    aborted_early = True
                    abort_reason = (
                        f"{consecutive_unreachable} consecutive unreachable probes."
                        " Inverter likely WLAN-dropped or rebooted; aborting before"
                        " further probing destabilises it further."
                    )
                    print(f"[probe] WATCHDOG TRIPPED — {abort_reason}", file=sys.stderr)
                    break
            else:
                consecutive_unreachable = 0

            # Rate limit between probes (skipped after the last one).
            if index < len(endpoints):
                time.sleep(rate_limit_seconds)

    finished_at = datetime.now(tz=UTC)
    by_outcome: dict[str, int] = {}
    for r in results:
        by_outcome[r.outcome] = by_outcome.get(r.outcome, 0) + 1

    metadata = RunMetadata(
        started_at_utc=started_at.isoformat(),
        finished_at_utc=finished_at.isoformat(),
        host=host,
        port=port,
        timeout_seconds=timeout_seconds,
        rate_limit_seconds=rate_limit_seconds,
        consecutive_fail_limit=consecutive_fail_limit,
        aborted_early=aborted_early,
        abort_reason=abort_reason,
        total_probes=len(results),
        by_outcome=by_outcome,
    )
    return metadata, results


def write_findings(
    *,
    output_path: Path,
    metadata: RunMetadata,
    results: list[ProbeResult],
) -> None:
    payload = {
        "metadata": asdict(metadata),
        "results": [asdict(r) for r in results],
    }
    output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(f"[probe] wrote {output_path}", file=sys.stderr)


# --- CLI --------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Probe an APsystems EZ1-M local HTTP API for documented and"
            " undocumented endpoints. Read-only by design."
        )
    )
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--timeout-seconds", type=float, default=DEFAULT_TIMEOUT_SECONDS)
    parser.add_argument("--rate-limit-seconds", type=float, default=DEFAULT_RATE_LIMIT_SECONDS)
    parser.add_argument(
        "--consecutive-fail-limit",
        type=int,
        default=DEFAULT_CONSECUTIVE_FAIL_LIMIT,
        help="Abort after N consecutive unreachable probes (watchdog).",
    )
    parser.add_argument(
        "--no-set-endpoints",
        action="store_true",
        help=(
            "Skip the existence probe of set*-style endpoints."
            " Use when even an OPTIONS-equivalent traffic pattern is undesired."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent,
        help="Directory to write findings-<timestamp>.json into.",
    )
    args = parser.parse_args(argv)

    metadata, results = run_discovery(
        host=args.host,
        port=args.port,
        timeout_seconds=args.timeout_seconds,
        rate_limit_seconds=args.rate_limit_seconds,
        consecutive_fail_limit=args.consecutive_fail_limit,
        include_set_endpoints=not args.no_set_endpoints,
    )

    timestamp = metadata.started_at_utc.replace(":", "-").split(".")[0]
    output_path = args.output_dir / f"findings-{timestamp}Z.json"
    write_findings(output_path=output_path, metadata=metadata, results=results)

    print(
        "[probe] done. "
        + ", ".join(f"{outcome}={count}" for outcome, count in metadata.by_outcome.items()),
        file=sys.stderr,
    )

    return 1 if metadata.aborted_early else 0


if __name__ == "__main__":
    sys.exit(main())
